name: "Store Metadata in MongoDB"
description: "Extract metadata and store it in MongoDB"
inputs:
  target_directory:
    description: "The directory containing the code to process"
    required: true
    default: "/github/workspace"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "${{ inputs.target_directory }}"